# Generated by Django 2.0.7 on 2018-07-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='type',
            field=models.CharField(blank=True, choices=[('Django', 'DJANGO'), ('Wordpress', 'WORDPRESS')], default='BLANK', max_length=6),
        ),
    ]
