# Generated by Django 2.0.7 on 2018-07-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20180723_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='type',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Wordpress', 'Wordpress')], default='BLANK', max_length=100),
        ),
    ]
