# Generated by Django 2.0.7 on 2018-07-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20180723_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sites',
            name='type',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Wordpress', 'Wordpress')], max_length=100),
        ),
    ]
